### ISSUE TITLE
Unable to build with rust 1.65 - error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants

### ISSUE THREAD

**Issue by berrange** [virtee/sev#83]
Attempting to build sevctl on Ubuntu 22.04 distro fails with:

```
$ cargo build
   Compiling env_logger v0.10.0
   Compiling x509-parser v0.14.0
   Compiling sev v1.2.0
error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants
   --> /home/azureuser/.cargo/registry/src/github.com-1ecc6299db9ec823/sev-1.2.0/src/error.rs:366:20
    |
271 |     IoError(io::Error),
    |     ------------------ tuple variant defined here
...
366 |     RbModeExited = 0x001F, // 0x001F
    |                    ^^^^^^ disallowed custom discriminant
...
369 |     RMPInitRequired = 0x0020, // 0x0020
    |                       ^^^^^^ disallowed custom discriminant
    |
    = note: see issue #60553 <https://github.com/rust-lang/rust/issues/60553> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `sev` due to previous error
warning: build failed, waiting for other jobs to finish...
```

This is the OS info:

```
$ rustc --version
rustc 1.65.0
$ cargo --version
cargo 1.65.0
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

IIUC, the error indicates sev is relying on a fairly new rust language feature which feels undesirable, when even the relatively modern Ubuntu 22.04 LTS release can't cope with it.

**Comment by tylerfanelli** [comment]
I'm surprised this is disallowed, setting discriminate values for enums?

I guess a workaround we could do is remove the custom discriminant from the enum:
```
pub enum IoError {
    ..snip..
    RbModeExited,
    ...snip..
}
```

and then for finding this value, we impl the TryInto trait for the enum.

```
impl TryInto<usize> for IoError {
    type Error = _;

    fn try_into(self) -> Result<usize> {
        match self {
             ..snip..
             IoError::RbModeExited => Ok(0x001F),
             ..snip..
    }
}
```

@larrydewey what do you think?

**Comment by tylerfanelli** [comment]
@larrydewey Why are the enum values of `RbModeExited` and `RMPInitRequired` set explicitly? They're the only two treated like this in the `Error` enum

https://github.com/virtee/sev/blob/a5c9eb231cea1a1233e57b6e34a1bdd05809e364/src/error.rs#L268-L391

**Comment by larrydewey** [comment]
> @larrydewey Why are the enum values of `RbModeExited` and `RMPInitRequired` set explicitly? They're the only two treated like this in the `Error` enum
> 
> https://github.com/virtee/sev/blob/a5c9eb231cea1a1233e57b6e34a1bdd05809e364/src/error.rs#L268-L391

We are manually setting the discriminant because we are skipping `0x1E`. I don't believe there is a known status for the value of `0x1E` at this point, so we could set a reserved field here to make sure `RbModeExited` is assigned the correct enumeration value, but if one gets added in the future we would obviously need to account for that and adjust.

**Comment by tylerfanelli** [comment]
@larrydewey Thanks. Yes, we could just have `Error::Reserved` and leave a note that it's just a placeholder and shouldn't be used. Either that, or we go with a newer (>= 1.66) Rust version as a minimum. As major OSes like Ubuntu are not even caught up with that version number yet, I don't think that's the way to go, and can lead to more headaches down the line.

**Comment by tylerfanelli** [comment]
Per [here](https://github.com/virtee/sev/pull/89#issuecomment-1644649677), can you try updating the rust package on 22.04 and seeing if this fixes the issue?

**Comment by larrydewey** [comment]
Ubuntu pushed out a security update to patch to Rust version 1.66.1. We have merged a PR which sets the Rust minimum version to this. @berrange feel free to re-open if you have any concerns.
